// <auto-generated />
using GestorEstudiantil.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GestorEstudiantil.DataAccess.Migrations
{
    [DbContext(typeof(GestorEstudiantilDBContext))]
    [Migration("20171031212738_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("GestorEstudiantil.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Asistio");

                    b.Property<int>("EstudianteMatriculadoId");

                    b.Property<DateTime>("FechaAsistencia");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("EstudianteMatriculadoId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("GestorEstudiantil.Models.Estudiante", b =>
                {
                    b.Property<string>("EstudianteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Nombres");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("GestorEstudiantil.Models.EstudianteMatriculado", b =>
                {
                    b.Property<int>("EstudianteMatriculadoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EstudianteId");

                    b.Property<string>("EstudianteId1");

                    b.Property<DateTime>("FechaMatricula");

                    b.Property<int>("SemestreMateriaId");

                    b.HasKey("EstudianteMatriculadoId");

                    b.HasIndex("EstudianteId1");

                    b.HasIndex("SemestreMateriaId");

                    b.ToTable("EstudianteMatriculado");
                });

            modelBuilder.Entity("GestorEstudiantil.Models.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NombreMateria");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("GestorEstudiantil.Models.Semestre", b =>
                {
                    b.Property<int>("SemestreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NombreSemestre");

                    b.HasKey("SemestreId");

                    b.ToTable("Semestres");
                });

            modelBuilder.Entity("GestorEstudiantil.Models.SemestreMateria", b =>
                {
                    b.Property<int>("SemestreMateriaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MateriaId");

                    b.Property<int>("SemestreId");

                    b.HasKey("SemestreMateriaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("SemestreId");

                    b.ToTable("SemestreMaterias");
                });

            modelBuilder.Entity("GestorEstudiantil.Models.Asistencia", b =>
                {
                    b.HasOne("GestorEstudiantil.Models.EstudianteMatriculado", "EstudianteMatriculado")
                        .WithMany("Asistencias")
                        .HasForeignKey("EstudianteMatriculadoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GestorEstudiantil.Models.EstudianteMatriculado", b =>
                {
                    b.HasOne("GestorEstudiantil.Models.Estudiante", "Estudiante")
                        .WithMany("Matriculas")
                        .HasForeignKey("EstudianteId1");

                    b.HasOne("GestorEstudiantil.Models.SemestreMateria", "SemestreMateria")
                        .WithMany("EstudiantesAsociados")
                        .HasForeignKey("SemestreMateriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GestorEstudiantil.Models.SemestreMateria", b =>
                {
                    b.HasOne("GestorEstudiantil.Models.Materia", "Materia")
                        .WithMany("Materias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GestorEstudiantil.Models.Semestre", "Semestre")
                        .WithMany("Materias")
                        .HasForeignKey("SemestreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
